#!/usr/bin/env python
# -*- encoding: utf-8 -*-
#

"""Print the file containing the given Python module."""

import os
import sys
from importlib import import_module


def main():
    if len(sys.argv) != 2:
        print >> sys.stderr, "Usage: %s MODULE" % sys.argv[0]
        return 1

    module_name = sys.argv[1]
    module = import_module(module_name)
    try:
        file_ = module.__file__
    except AttributeError:
        raise RuntimeError("Module %s has no file! Maybe it is a"
                           " built in module?\n" % module_name)

    if file_.endswith(".pyc"):
        file_ = file_[:-4] + ".py"

    print file_


if __name__ == "__main__":
    sys.exit(main())
